kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pvc-claim
  namespace: es
spec:
  storageClassName: nfs-slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

